### ISSUE TITLE
Sharing the whole vault

### ISSUE THREAD

**Issue by KucharczykL** [Mara-Li/mkdocs_obsidian_publish#3]
Is there a way to share the whole vault? I would like to have a private instance of my Obsidian vault and adding `share: true` to ALL my notes is not feasbile.

**Comment by Mara-Li** [comment]
1. I can create a option to skip vault = share, but it needs a lot of work because everything is based on that.
2. I can write a little python script to add a YAML value to share all file in a folder. BUT, if the script crash : RIP your file.
3. You can use folder note + metaedit to add a key in all note in a folder (it's the only plugin I know that do that)
4. You can open your vault with VSCode, and edit all the yaml with using : 
 - Search all (CTRL + MAJ + F)
 - Use a regex expression (ALT + R) : `---\n`
 - Replace with : `---\nshare: true\n`
It's the best way to share all the file, without breaking everything.

Note that I don't try to share a big vault, so I hope the script will work and don't be too much long.

**Comment by KucharczykL** [comment]
I would prefer not to edit all my notes but I understand that adding this feature would be additional work for you.

**Comment by Mara-Li** [comment]
As my programming is a little chaotique, I'm afraid that adding this option can break everything, as I do a lot of check for this. I will consider adding this option!

**Comment by Mara-Li** [comment]
Hello! I add the option this morning. I try it, and I think it works without problem.

Don't forget that, without `--meta` the script will don't update the sharing state, so you need to always use `--vault` to share everything!

It was little quick because the option already exist because of the `convert one` so I just add an option for sharing all.

**Comment by KucharczykL** [comment]
Thank you so much! It works great :)
